#!/usr/bin/env bun
/**
 * Patches auto-generated SDK files to add error logging.
 *
 * This script should be run after @hey-api/openapi-ts regenerates the client.
 * It adds console.error logging for JSON parse failures that would otherwise
 * be silently caught.
 *
 * Run: bun ./script/patch-generated.ts
 */

import fs from "fs"
import path from "path"

const dir = new URL("..", import.meta.url).pathname

const patches: Array<{
  file: string
  description: string
  find: string
  replace: string
}> = [
  {
    file: "src/gen/core/serverSentEvents.gen.ts",
    description: "Add SSE JSON parse error logging",
    find: `                try {
                  data = JSON.parse(rawData)
                  parsedJson = true
                } catch {
                  data = rawData
                }`,
    replace: `                try {
                  data = JSON.parse(rawData)
                  parsedJson = true
                } catch (parseError) {
                  console.error("[SDK] SSE JSON parse error:", {
                    url,
                    eventName,
                    rawData: rawData.substring(0, 500),
                    error: parseError,
                  })
                  data = rawData
                }`,
  },
  {
    file: "src/gen/core/serverSentEvents.gen.ts",
    description: "Add SSE connection error logging",
    find: `      } catch (error) {
        // connection failed or aborted; retry after delay
        onSseError?.(error)`,
    replace: `      } catch (error) {
        // connection failed or aborted; retry after delay
        console.error("[SDK] SSE connection error:", { url, attempt, error })
        onSseError?.(error)`,
  },
  {
    file: "src/gen/client/client.gen.ts",
    description: "Add API error response JSON parse error logging",
    find: `    try {
      jsonError = JSON.parse(textError)
    } catch {
      // noop
    }`,
    replace: `    try {
      jsonError = JSON.parse(textError)
    } catch (parseError) {
      // Log JSON parse failure for error responses
      if (textError.trim().startsWith("{") || textError.trim().startsWith("[")) {
        console.error("[SDK] API error response JSON parse failure:", {
          url: request.url,
          status: response.status,
          rawBody: textError.substring(0, 500),
          error: parseError,
        })
      }
    }`,
  },
]

// Add header comment to patched files
const headerComment = "// NOTE: Manual modifications for error logging - will be overwritten on regeneration\n"

let success = true

for (const patch of patches) {
  const filePath = path.join(dir, patch.file)

  if (!fs.existsSync(filePath)) {
    console.error(`[SKIP] File not found: ${patch.file}`)
    continue
  }

  let content = fs.readFileSync(filePath, "utf-8")

  // Add header comment if not already present
  if (!content.includes("Manual modifications for error logging")) {
    content = content.replace(
      "// This file is auto-generated by @hey-api/openapi-ts\n",
      "// This file is auto-generated by @hey-api/openapi-ts\n" + headerComment
    )
  }

  // Apply patch
  if (content.includes(patch.find)) {
    content = content.replace(patch.find, patch.replace)
    fs.writeFileSync(filePath, content)
    console.log(`[OK] ${patch.description} (${patch.file})`)
  } else if (content.includes(patch.replace)) {
    console.log(`[SKIP] Already patched: ${patch.description}`)
  } else {
    console.error(`[FAIL] Could not find pattern for: ${patch.description}`)
    console.error(`       File: ${patch.file}`)
    success = false
  }
}

if (success) {
  console.log("\nAll patches applied successfully!")
} else {
  console.error("\nSome patches failed. The generated code may have changed.")
  process.exit(1)
}
